Fixed some train bugs
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Fixed all path issues with config
Improved print